CREATE DATABASE shopping_db;
use shopping_db;
select * from customer_shopping limit 10;

-- --Total Revenue Generated by Male and female 
select gender ,sum(purchase_amount) from customer_shopping
group by  gender;

-- Pay higher than avg amount after using discount by customer
select customer_id , purchase_amount from customer_shopping
where discount_applied = 'Yes' and purchase_Amount >= (select avg(purchase_Amount) from customer_shopping);

-- Top 5 product with the highest average rating review
select item_purchased , round(avg(review_rating ),2) as "Average Review Rating" from customer_shopping
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Compare average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_Amount),2) from customer_shopping 
where shipping_type in ("standard","express")
group by shipping_type

-- Compare average spend and total revenue between subcriber and non subcribers 
select subscription, COUNT(CUSTOMER_id) as total_customer,
round(avg(purchase_amount),1) as average_spend, sum(purchase_amount) as total_revenue from customer_shopping
where subscription in ("Yes" and "No")
group by subscription
order by average_spend,total_revenue desc;

-- Top 5 highest percentage of purchases with discound applied
select item_purchased, round(sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) * 100,2) as discount_percentage
from customer_shopping
group by item_purchased
order by discount_percentage desc
limit 5 

-- SELECT 
--     item_purchased,
--     ROUND(
--         AVG(discount_applied = 'Yes') * 100,
--         2
--     ) AS discount_percentage
-- FROM customer_shopping
-- GROUP BY item_purchased
-- ORDER BY discount_percentage DESC
-- LIMIT 5;

-- Segment customer into  new,returning, loyal based on their total number of previous purchase and count of each segment
with customer_type as(
select customer_id , previous_purchases,
case 
    when previous_purchases = 1 then "New"
	when previous_purchases between 2 and 10 then "Returning"
	else "Loyal" end as customer_segment from customer_shopping )
select customer_Segment, count(*) as "Number of Customer" from customer_type
group by customer_segment;

-- SELECT 
--     CASE
--         WHEN previous_purchases = 1 THEN 'New'
--         WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
--         ELSE 'Loyal'
--     END AS customer_segment,
--     COUNT(*) AS customer_count
-- FROM customer_shopping
-- GROUP BY customer_segment
-- ORDER BY customer_count DESC;

-- Top 3 most purchased product by category
with item_count as (
select category, item_purchased,
count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category,item_purchased)

select category,total_order,item_purchased,item_rank
from item_count
where  item_rank <=3;

-- Repeat buyer more than 5 by previous purchases
select subscription,
count(customer_id) as Repeat_customer
from customer_shopping
where previous_purchases >5
group by subscription;

-- Revenue contribution of each age group
select age_group,
sum(purchase_Amount) as Total_Revenue
from customer_shopping
group by age_group
order by total_revenue;